### ISSUE TITLE
function fait_isolignes would missing isothermal line inside saturation zone due to inf value in calculation

### ISSUE THREAD

**Issue by daqingli616** [jjfPCSI1/py4phys#2]
I tried T6_diagramme_Ph_coolprop.py and other codes that has the fait_isolignes in there. I found out that sometimes there is a missing section inside the two-phase zone for the iso-temperature line. By checking the calculated [P,H] values, it is clear that due to sometimes a "inf" value is returned from coolprop function, that point will be skipped by the plot function and causes a missing segment of iso-thermal line inside the two-phase zone.
[T6_diagramme_Ph_coolprop_refrigerateur_R410A.pdf](https://github.com/jjfPCSI1/py4phys/files/4582035/T6_diagramme_Ph_coolprop_refrigerateur_R410A.pdf)

**Comment by jjfPCSI1** [comment]
It's seemed to be related to pressure getting exactly the value of the saturation pressure for these temperatures. It should be corrected with commit acbc230f80160dcb9d13ee9cae4c19f01dd0970c concerning only the R410A file. Could you please see if it's correct for you so that I can backport in other files ?
